const AUTO_SERVICE_DESCRIPTION_PATTERNS = [
  "a tailored appointment shaped around the client profile, beauty goals, and preferred booking window.",
  "atendimento personalizado, planejado de acordo com perfil, objetivo, rotina e preferencia de agendamento da cliente.",
  "atendimento personalizado, planejado de acordo com perfil, objetivo, rotina e preferência de agendamento da cliente.",
] as const;

function normalizeText(value: string) {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/\s+/g, " ")
    .trim();
}

export function isAutoGeneratedServiceDescription(value?: string | null) {
  const normalizedValue = normalizeText(value ?? "");

  if (!normalizedValue) {
    return false;
  }

  return AUTO_SERVICE_DESCRIPTION_PATTERNS.some(
    (pattern) => normalizeText(pattern) === normalizedValue,
  );
}

export function stripAutoGeneratedServiceDescription(value?: string | null) {
  if (!value) {
    return "";
  }

  return isAutoGeneratedServiceDescription(value) ? "" : value.trim();
}
