import { ArrowUpRight, ExternalLink, MapPin, Menu, Star } from "lucide-react";
import { BeforeAfterSlider } from "./BeforeAfterSlider";
import { FeedbackScreenshotCarousel } from "./FeedbackScreenshotCarousel";
import { StaticImage } from "./StaticImage";
import { buildWhatsappHref, imageById, salon } from "../../../lib/salon";
import type { StaticAsset } from "../../../lib/types";

export function StaticPremiumV1() {
  const content = salon.premiumEditorial;
  const imageMap = new Map(salon.images.map((image) => [image.id, image]));
  const heroImage = imageById(content.heroImageId) ?? firstUsableImage(salon.images);
  const aboutImage = imageById(content.aboutImageId) ?? heroImage;
  const beforeAfterItems = content.beforeAfterItems
    .filter((item) => item.enabled)
    .sort((first, second) => first.order - second.order)
    .map((item) => ({ item, before: imageMap.get(item.beforeImageId), after: imageMap.get(item.afterImageId) }))
    .filter((entry): entry is { item: typeof entry.item; before: StaticAsset; after: StaticAsset } => Boolean(entry.before && entry.after));
  const faqItems = content.faqItems.filter((item) => item.enabled && item.question.trim() && item.answer.trim()).sort((first, second) => first.order - second.order);
  const accent = content.accentColor || "#9b7353";
  const background = content.backgroundColor || "#f8f5f0";
  const finalCtaBackground = content.finalCtaBackgroundColor || "#281916";
  const finalWhatsappButtonColor = content.finalWhatsappButtonColor || "#25D366";
  const finalWhatsappButtonTextColor = content.finalWhatsappButtonTextColor || "#ffffff";
  const bookingButtonTextColor = content.bookingButtonTextColor || "#ffffff";
  const instagramButtonTextColor = content.instagramButtonTextColor || "#281916";
  const labels = getLabels();
  const primaryHref = salon.bookingUrl || buildWhatsappHref();

  return (
    <main className="min-h-screen overflow-x-hidden text-zinc-950" style={{ backgroundColor: background }}>
      <header className="sticky top-0 z-50 border-b border-zinc-900/10 bg-white/85 backdrop-blur-xl">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 sm:px-8 lg:px-10">
          <a href="#top" className="flex min-w-0 items-center" aria-label={salon.name}>
            {salon.horizontalLogo ? <span className="block" style={{ width: "clamp(210px, 66vw, 390px)", maxWidth: "calc(100% - 64px)", height: "clamp(40px, 8vw, 68px)" }}><StaticImage image={salon.horizontalLogo} alt={`${salon.name} — logo`} priority sizes="(max-width: 430px) 235px, (max-width: 768px) 285px, (max-width: 1024px) 340px, 390px" className="h-full w-full object-contain object-left" /></span> : <span className="truncate font-serif text-lg font-semibold tracking-tight sm:text-xl">{salon.name}</span>}
          </a>
          <nav className="hidden items-center gap-7 text-[0.82rem] font-medium text-zinc-700 md:flex">
            <a href="#about" className="transition hover:text-zinc-950">{labels.about}</a><a href="#services" className="transition hover:text-zinc-950">{labels.services}</a>{beforeAfterItems.length ? <a href="#results" className="transition hover:text-zinc-950">{labels.results}</a> : null}<a href="#contact" className="transition hover:text-zinc-950">{labels.contact}</a>
          </nav>
          <div className="flex items-center gap-2">
            <a href={primaryHref} className="hidden rounded-full px-4 py-2 text-[0.82rem] font-semibold shadow-sm transition hover:-translate-y-0.5 md:inline-flex" style={{ backgroundColor: accent, color: bookingButtonTextColor }}>{labels.bookAppointment}</a>
            <details className="relative md:hidden"><summary className="flex h-10 w-10 cursor-pointer list-none items-center justify-center rounded-full border border-zinc-200 bg-white"><Menu className="h-5 w-5" /></summary><div className="absolute right-0 top-12 grid min-w-44 gap-2 rounded-2xl border border-zinc-200 bg-white p-3 text-sm shadow-2xl"><a href="#about" className="rounded-xl px-3 py-2 hover:bg-zinc-50">{labels.about}</a><a href="#services" className="rounded-xl px-3 py-2 hover:bg-zinc-50">{labels.services}</a>{beforeAfterItems.length ? <a href="#results" className="rounded-xl px-3 py-2 hover:bg-zinc-50">{labels.results}</a> : null}<a href="#contact" className="rounded-xl px-3 py-2 hover:bg-zinc-50">{labels.contact}</a></div></details>
          </div>
        </div>
      </header>

      <section id="top" className="mx-auto grid max-w-7xl gap-10 px-5 pb-0 pt-12 sm:px-8 md:pb-24 md:pt-20 lg:grid-cols-[0.8fr_1.2fr] lg:items-center lg:px-10 lg:pt-24">
        <div className="max-w-xl"><p className="text-[0.68rem] font-semibold uppercase tracking-[0.22em]" style={{ color: accent }}>{content.heroEyebrow}</p><h1 className="mt-4 max-w-2xl font-serif text-[2.75rem] leading-[0.96] tracking-tight sm:text-6xl lg:text-[6rem]">{content.heroTitle || salon.name}</h1>{content.heroDescription ? <p className="mt-6 max-w-lg text-[0.95rem] leading-7 text-zinc-600 sm:text-base">{content.heroDescription}</p> : null}<div className="mt-7 flex flex-wrap gap-3"><a href={primaryHref} className="inline-flex items-center gap-2 rounded-full px-5 py-2.5 text-[0.82rem] font-semibold shadow-lg transition hover:-translate-y-0.5" style={{ backgroundColor: accent, color: bookingButtonTextColor }}>{labels.bookAppointment}<ArrowUpRight className="h-4 w-4" /></a>{salon.instagramUrl ? <a href={salon.instagramUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full border border-zinc-300 bg-white/70 px-5 py-2.5 text-[0.82rem] font-semibold transition hover:bg-white" style={{ color: instagramButtonTextColor }}><InstagramIcon />Instagram</a> : null}</div></div>
        <div className="relative aspect-[4/5] overflow-hidden rounded-[2rem] bg-zinc-200 sm:rounded-[3rem]">{heroImage ? <StaticImage image={heroImage} alt={`${salon.name} hero`} priority sizes="(min-width: 1024px) 58vw, 100vw" className="h-full w-full object-cover" /> : <ImageFallback />}</div>
      </section>

      <section id="about" className="bg-white px-5 pb-14 pt-12 sm:px-8 md:py-24 lg:px-10"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-[0.85fr_1.15fr] lg:items-center"><div className="order-2 relative aspect-[4/5] overflow-hidden rounded-[2rem] bg-zinc-100 sm:rounded-[3rem] lg:order-1">{aboutImage ? <StaticImage image={aboutImage} alt={`${salon.name} portrait`} sizes="(min-width: 1024px) 38vw, 100vw" className="h-full w-full object-cover" /> : <ImageFallback />}</div><div className="order-1 max-w-xl lg:order-2"><p className="text-[0.68rem] font-semibold uppercase tracking-[0.22em]" style={{ color: accent }}>{labels.about}</p><h2 className="mt-5 font-serif text-[2.1rem] leading-tight sm:mt-4 sm:text-5xl">{content.aboutTitle}</h2>{content.aboutRole ? <p className="mt-6 text-[0.68rem] font-semibold uppercase tracking-[0.16em] text-zinc-500 sm:mt-4">{content.aboutRole}</p> : null}{content.aboutText ? <p className="mt-7 whitespace-pre-line text-[0.92rem] leading-[1.7] text-zinc-600 sm:mt-6 sm:text-base sm:leading-7">{content.aboutText}</p> : null}</div></div></section>

      {salon.services.length ? <section id="services" className="bg-white px-5 pb-14 pt-12 sm:px-8 md:py-24 lg:px-10"><div className="mx-auto max-w-6xl"><p className="text-[0.68rem] font-semibold uppercase tracking-[0.22em]" style={{ color: accent }}>{labels.services}</p><h2 className="mt-3.5 max-w-2xl font-serif text-[2.05rem] leading-tight sm:text-4xl">{labels.servicesTitle}</h2><div className="mt-6 border-y border-zinc-200">{salon.services.map((service, index) => <article key={service.id} className="grid grid-cols-[3rem_1fr] gap-x-3 gap-y-2 border-b border-zinc-200/80 py-6 last:border-b-0 sm:grid-cols-[5rem_1fr_auto] sm:items-start sm:gap-4 sm:py-7"><span className="pt-1 font-serif text-lg text-[#b48b82] sm:text-xl">{String(index + 1).padStart(2, "0")}</span><div><h3 className="font-serif text-[1.2rem] leading-tight sm:text-xl">{service.title}</h3>{service.description ? <p className="mt-2 max-w-2xl text-[0.82rem] leading-[1.55] text-zinc-600 sm:text-[0.9rem]">{service.description}</p> : null}</div>{salon.bookingUrl ? <a href={salon.bookingUrl} target="_blank" rel="noreferrer" className="col-start-2 inline-flex items-center gap-1 text-[0.78rem] font-semibold sm:col-start-auto" style={{ color: accent }}>{labels.serviceCta}<ArrowUpRight className="h-4 w-4" /></a> : null}</article>)}</div>{(salon.bookingUrl || salon.whatsapp) ? <div className="mt-6 text-center"><a href={salon.whatsapp ? buildWhatsappHref() : primaryHref} className="inline-flex items-center gap-2 rounded-full border border-transparent px-6 py-3 text-[0.82rem] font-semibold shadow-lg transition hover:-translate-y-0.5 hover:brightness-95" style={{ backgroundColor: accent, color: bookingButtonTextColor }}>{labels.bookViaWhatsapp}<ArrowUpRight className="h-4 w-4" /></a></div> : null}</div></section> : null}

      {beforeAfterItems.length ? <section id="results" className="px-5 pb-14 pt-12 sm:px-8 md:py-20 lg:px-10"><div className="mx-auto max-w-6xl"><p className="text-[0.62rem] font-semibold uppercase tracking-[0.24em]" style={{ color: accent }}>{labels.results}</p><h2 className="mt-2.5 max-w-xl font-serif text-[2.05rem] leading-tight sm:text-4xl">{labels.beforeAfterTitle}</h2><p className="mt-2.5 max-w-xl text-[0.82rem] leading-6 text-zinc-500">{labels.beforeAfterDescription}</p><div className="mt-7 grid gap-7 md:grid-cols-2">{beforeAfterItems.map(({ item, before, after }) => <article key={item.id} className="overflow-hidden rounded-[2rem] bg-white shadow-[0_20px_60px_rgba(24,24,27,0.08)]"><BeforeAfterSlider beforeImage={before} afterImage={after} title={item.title} beforeLabel={labels.before} afterLabel={labels.after} adjustLabel={labels.adjustComparison} /><div className="p-4"><h3 className="font-serif text-xl">{item.title}</h3>{item.description ? <p className="mt-1.5 text-[0.82rem] leading-6 text-zinc-600">{item.description}</p> : null}</div></article>)}</div></div></section> : null}

      <Reviews accent={accent} />
      {(content.methodEyebrow || content.methodTitle || content.methodText) ? <section className="px-5 pb-10 pt-8 sm:px-8 md:py-16 lg:px-10"><div className="mx-auto grid max-w-6xl gap-5 lg:grid-cols-[0.7fr_1.3fr]"><div><p className="text-[0.62rem] font-semibold uppercase tracking-[0.22em]" style={{ color: accent }}>{content.methodEyebrow}</p><h2 className="mt-3 font-serif text-[1.7rem] leading-tight sm:text-4xl">{content.methodTitle}</h2></div>{content.methodText ? <p className="max-w-2xl self-end text-[0.9rem] leading-[1.6] text-zinc-600 sm:text-base sm:leading-7">{content.methodText}</p> : null}</div></section> : null}
      {faqItems.length ? <section className="px-5 pb-8 pt-10 sm:px-8 md:py-24 lg:px-10"><div className="mx-auto max-w-4xl"><p className="text-[0.68rem] font-semibold uppercase tracking-[0.22em]" style={{ color: accent }}>FAQ</p><div className="mt-6 divide-y divide-zinc-300 border-y border-zinc-300">{faqItems.map((item) => <details key={item.id} className="group py-4"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 font-serif text-lg leading-[1.2] marker:hidden"><span>{item.question}</span><span className="font-sans text-xl font-normal" style={{ color: accent }}>+</span></summary><p className="mt-2.5 max-w-2xl whitespace-pre-line text-[0.82rem] leading-6 text-zinc-600">{item.answer}</p></details>)}</div></div></section> : null}
      <section id="contact" className="px-5 py-20 text-center text-[#f7eee8] sm:px-8 md:py-28 lg:px-10" style={{ backgroundColor: finalCtaBackground }}><div className="mx-auto max-w-3xl"><p className="text-[0.62rem] font-semibold uppercase tracking-[0.28em] text-[#c9988d]">{labels.reservations}</p><h2 className="mt-5 font-serif text-3xl leading-tight sm:text-5xl">{content.finalCtaTitle || "Secure Your Appointment"}</h2><div className="mx-auto mt-7 h-px w-20 bg-[#c9988d]/60" />{content.finalCtaText ? <p className="mx-auto mt-7 max-w-xl whitespace-pre-line text-[0.95rem] leading-7 text-[#d8c5bd] sm:text-base">{content.finalCtaText}</p> : null}<div className="mx-auto mt-8 grid max-w-md gap-3">{salon.bookingUrl ? <a href={salon.bookingUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-13 items-center justify-center gap-2 rounded-full bg-[#f7eee8] px-6 py-3 text-[0.9rem] font-semibold shadow-lg transition hover:-translate-y-0.5 hover:bg-white" style={{ color: bookingButtonTextColor }}>{labels.bookOnFresha}<ArrowUpRight className="h-4 w-4" /></a> : null}{salon.whatsapp ? <a href={buildWhatsappHref()} className="inline-flex min-h-13 items-center justify-center gap-2 rounded-full border border-transparent px-6 py-3 text-[0.9rem] font-semibold shadow-[0_12px_28px_rgba(37,211,102,0.22)] transition hover:-translate-y-0.5 hover:brightness-95" style={{ backgroundColor: finalWhatsappButtonColor, color: finalWhatsappButtonTextColor }}><WhatsAppIcon />{labels.chatOnWhatsapp}</a> : null}</div><div className="mt-8 grid gap-2 text-[0.82rem] text-[#bba49b]">{salon.address || salon.location ? <p className="flex items-center justify-center gap-2"><MapPin className="h-4 w-4" />{salon.address || salon.location}</p> : null}{salon.instagramUrl ? <a href={salon.instagramUrl} target="_blank" rel="noreferrer" className="flex items-center justify-center gap-2"><ExternalLink className="h-4 w-4" />Instagram</a> : null}</div></div></section>
    </main>
  );
}

function Reviews({ accent }: { accent: string }) {
  const content = salon.premiumEditorial;
  if (content.reviewDisplayType === "screenshots") {
    const items = content.reviewScreenshotImages.sort((first, second) => first.order - second.order).flatMap((item) => {
      const image = item.imageId ? imageById(item.imageId) : undefined;
      return image ? [{ id: item.id, image, alt: item.imageAlt || "Feedback de paciente" }] : [];
    });
    if (!items.length) return null;
    return <section className="bg-[#fbf8f5] px-5 pb-8 pt-8 sm:px-8 md:py-16 lg:px-10"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4 border-b border-zinc-200 pb-4"><div><p className="text-[0.62rem] font-semibold uppercase tracking-[0.24em]" style={{ color: accent }}>{content.reviewEyebrow || "O que dizem as pacientes"}</p><h2 className="mt-2.5 font-serif text-xl leading-tight sm:text-3xl">{content.reviewTitle || "Experiências que refletem nosso cuidado"}</h2>{content.reviewDescription ? <p className="mt-2.5 max-w-2xl text-[0.82rem] leading-6 text-zinc-500">{content.reviewDescription}</p> : null}</div></div><div className="mt-5"><FeedbackScreenshotCarousel accent={accent} items={items} /></div></div></section>;
  }

  const reviews = salon.testimonials.filter((review) => review.text).slice(0, 3);
  if (!reviews.length) return null;
  return <section className="bg-[#fbf8f5] px-5 pb-8 pt-8 sm:px-8 md:py-16 lg:px-10"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4 border-b border-zinc-200 pb-4"><div><p className="text-[0.62rem] font-semibold uppercase tracking-[0.24em]" style={{ color: accent }}>Client love</p><h2 className="mt-2.5 font-serif text-xl leading-tight sm:text-3xl">What Our Clients Say</h2></div>{salon.googleRating ? <div className="flex items-center gap-2 text-[0.82rem] text-zinc-600"><span className="flex items-center gap-1" style={{ color: accent }}><Star className="h-3.5 w-3.5 fill-current" />{salon.googleRating.toFixed(1)}</span></div> : null}</div><div className="mt-5 grid gap-3 md:grid-cols-3">{reviews.map((review) => <figure key={review.id} className="rounded-[1.35rem] border border-zinc-200/80 bg-white p-4 shadow-[0_14px_34px_rgba(70,42,31,0.04)]"><div className="flex gap-1" style={{ color: accent }}>{Array.from({ length: Math.min(5, review.rating ?? 5) }).map((_, index) => <Star key={index} className="h-3.5 w-3.5 fill-current" />)}</div><blockquote className="mt-3 font-serif text-base leading-6 text-zinc-800">“{review.text}”</blockquote><figcaption className="mt-4 text-[0.62rem] font-semibold uppercase tracking-[0.16em] text-zinc-500">{review.authorName}</figcaption></figure>)}</div></div></section>;
}

function firstUsableImage(images: StaticAsset[]) { return images.find((image) => image.type !== "logo"); }
function ImageFallback() { return <div className="absolute inset-0 flex items-center justify-center bg-zinc-200 px-6 text-center font-serif text-3xl text-zinc-500">{salon.name}</div>; }
function InstagramIcon() { return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.9" className="h-[18px] w-[18px] shrink-0 text-[#b85c85]"><rect x="3.5" y="3.5" width="17" height="17" rx="4.5" /><circle cx="12" cy="12" r="4" /><circle cx="17.5" cy="6.5" r="0.65" fill="currentColor" stroke="none" /></svg>; }
function getLabels() {
  const content = salon.premiumEditorial;
  const portuguese = salon.language === "pt-BR";
  return {
    about: content.aboutLabel || (portuguese ? "Sobre" : "About"), services: content.servicesLabel || (portuguese ? "Serviços" : "Services"), servicesTitle: content.servicesTitle || (portuguese ? "Um menu pensado para cada mulher" : "A menu crafted for every woman"), results: content.resultsLabel || (portuguese ? "Resultados" : "Results"), contact: content.contactLabel || (portuguese ? "Contato" : "Contact"), bookAppointment: content.bookAppointmentLabel || (portuguese ? "Agendar atendimento" : "Book an appointment"), bookViaWhatsapp: content.bookViaWhatsappLabel || (portuguese ? "Agendar pelo WhatsApp" : "Book via WhatsApp"), reservations: content.reservationsLabel || (portuguese ? "Agendamentos" : "Reservations"), chatOnWhatsapp: content.chatOnWhatsappLabel || (portuguese ? "Conversar no WhatsApp" : "Chat on WhatsApp"), bookOnFresha: content.bookOnFreshaLabel || (portuguese ? "Agendar pelo Fresha" : "Book on Fresha"), serviceCta: portuguese ? "Agendar" : "Book", before: portuguese ? "Antes" : "Before", after: portuguese ? "Depois" : "After", beforeAfterTitle: portuguese ? "Antes e depois" : "Before & after", beforeAfterDescription: portuguese ? "Arraste para comparar as transformações selecionadas." : "Drag to compare selected transformations.", adjustComparison: portuguese ? "Ajustar comparação entre antes e depois" : "Adjust before and after comparison",
  };
}
function WhatsAppIcon() { return <svg viewBox="0 0 32 32" aria-hidden="true" className="h-5 w-5 fill-current"><path d="M16 3.1A12.8 12.8 0 0 0 5.2 22.7L3.4 28.8l6.3-1.7A12.9 12.9 0 1 0 16 3.1Zm0 23.4a10.5 10.5 0 0 1-5.3-1.4l-.4-.2-3.7 1 1-3.6-.2-.4A10.5 10.5 0 1 1 16 26.5Zm5.8-7.8c-.3-.2-1.8-.9-2.1-1-.3-.1-.5-.2-.7.2-.2.3-.8 1-.9 1.2-.2.2-.3.2-.6.1-1.7-.8-2.8-1.4-3.9-3.2-.3-.5.3-.5.8-1.6.1-.2.1-.4 0-.6-.1-.2-.7-1.7-1-2.3-.3-.6-.5-.5-.7-.5h-.6c-.2 0-.6.1-.9.4-.3.3-1.2 1.1-1.2 2.7s1.2 3.1 1.4 3.3c.2.2 2.3 3.5 5.5 4.9 2 .9 2.7 1 3.7.8.6-.1 1.8-.7 2.1-1.4.3-.7.3-1.3.2-1.4-.1-.1-.3-.2-.6-.4Z" /></svg>; }
